name: dart_utils_extension
description: 和UI 无关的扩展
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  collection: ^1.17.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
